### PR TITLE
Minor typo fix and added checks if unable to download file

### PR DESCRIPTION
**Pull request by ajinkya-kulkarni**

### CODE REVIEW

**Comment by JoOkuma** [comment]
Hi @ajinkya-kulkarni, thanks for the contribution.

I suggest updating the `get_weights_path` return type hint to `Optional[Path]` so it runs with `mypy`.
And, to leave the trailing spaces on the "Download complete" print, that's used to erase the previous output when using "\r".

**Comment by ajinkya-kulkarni** [comment]
Good point - done

**Comment by JoOkuma** [comment]
Thanks, I opened a PR to your `patch-1` branch to fix a few other things.

**Comment by JoOkuma** [comment]
I'll merge when the tests are done, thanks!

**Comment by ajinkya-kulkarni** [comment]
Thanks!

**Pull request merged**
